pipeline:
  build:
    image: golang
    environment:
      - GOPATH=/drone
    commands:
      - go get
      - go build
      - go test
  slack:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: general

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_DB=gcon_test
