language: go
services:
- postgresql
- docker
env:
  matrix:
  - PATH=/home/travis/gopath/bin:$PATH
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - IMAGE=bketelsen/gcon
  - IMAGE_VERSION=$IMAGE:$COMMIT
  - secure: FCDw2kxcCIb97cbQcTg9F+tDU7R+mmLb7ZUyjLCP+94aQaMzQhsU+6/Rqx+k7o/CsiQR3CCfUr+IyHgjiv0j19G8bFEbxZ/YlE+466FC+v/cDpXYbF6y+Q/+sNTZLB1rJG99na0BbNbsLR0tmE2slgO8UUbLr+O8j095GUWdYef5zeo7kpgC7qVEpCD+eV4Awz3EwH86gs9N2OG8flHg9FiRbqOsPo81dL6gl9f/OyCrN0KVTVMU360CxH3r2o5LWE45ZtXaSw1Th43tVkhZV+mNNo22EZMYoPzF7XxQi9SdXSWUYsHBGMPRe1Ea6OOJHqiDmQDOXFYEFgfP0jV07Ld2M/+pKL0p5MjK0K2CYXERNB0DHDkiEV8akFh/szmAkhhbUlPrhkeGS7iADaUdw+7kwFatohWfwSeqjBrL4ousAIpvYp7Bub+DuXysRmexi5UG8HF6F8lD0paY6idPxpx7xXG/njwvi247X/6unrKzXSynsyH6V0kT0nz7Y+os791eMYDwgIOnSe+eTreTL74Sc3RbQhMmRQVeJeuIFsiMhU+lGjOI4S84YaIYwdWRjkjIzVLaSrd2JNc1rw01JzbhAI0n1CV1cc2L+r4we5FA+Qv249EqI8Jn0S0O+TEy1QW2F442s3fo/HB4ozUoByvNAy6L68a/HWbX5ZzSxnM=
  - secure: P0OHDe3KI3X07CwuIlB/hFfvQu0L4CZdBNAiqOk8TcEzivLuntcpzhnuxkQt0qtSAxVVMtOF8K5GMU7qitzjZ4OH/5CNnnjsYn3l7RBQ6NW9WmiqQ20/PXJIgTDoelZ6ZS7bFbTT00uRUROW8jyJx1qJ3muahLOJ6fS/SX15gneCOvlgpIYIF/Xi1CEd2R1ZyOOTZYM9yiKt0h2Ob+bddrMvM8DzHlxCGVkCQpfRmHjJ1Befso+MtSAJK8Ek49nXBj+U0beKMgkqRL+4TH4VW9PwKTbfL6t1DtDR3xFalo6Hov3LRaGwbIgB2kWdmhIAXFKm7oxZ2D6GiRCPHlfbj4cxXYDvv8rlidOCrMJ0KYBmYyLf5TlBXIq7D8wvHlFtztC7hOmhqryytack4vkn5gvfB3AR0fs2S6KTXoCJXRESTIhPGzgFeDUDUYOEx72GekGzSkRIxarNs4ZUqHrCgs+mouVEBhJKqsqeaW8JZorl12yFTgxdvkgVd7v08qH5a4mGgFP7KuLulxw34g+Dy+idBorwGpKQU+7Iuw/I1i7zLWmOmTdQ02zYEnknWU1Whr4oBoVw3BwmNQBM6Yx4fYWqIYRVgpCmy4W9Oflu5OEddFcvacYBWV2X+JEnfUrh+3kuKsxSyOHgCewMvTqlGeAVcS8I1L9ww/wTyqSjruQ=
  - secure: ciovv49/gkDwySIFjN8lYGxPTBCtv6sv8HovoRsbLlwAEfl9zqI2ejJuUFCAuUP43zJKZUoKW9zMz4xtKv5cvrPB5pWCglf5bQ/92SBPDh9VFfsu0fzbDpUJEhVqG4lxc+cUOz2GjT5LY69YRcbOVua+noJO05NRjN5Zk1tE44xid9JEeSAwo7PWbMbZaHQK6eF3DK0aZr9hVqDMI9zoEdiRSh+07blLuFrqVBkYLmTNUWL1O9bnlf3kkRD2oAt68T9N1WeZ/D7GdM5RGCCwvLI9QKA6umQ9ZE1/kXp77kfSwzJ7XYxRdr7SekmhPEVl+kUF53eRDpmUNtLJhQmUqjL+zW1sGfwOTDu7Gv0jHkp9fI6je2jVWysL0MuRDQLaEs9HVX7M9ap1Sjy3GxbTzBaUDAj3QDHCMlQWTcPcS59TzX43PH6fiV+VxXQIRVc+zC/pow6SA1Dohs6BGBqICo2121Vznr8t9nosOZhC7BVtDCwaQFtqp9CPSXYAOYEZnev8dZlYoaXtRRMY5S++qaXjSZFaU7ubyZboPI+A3D8Sv5JjTq9S8JnkvV5Y4zoKaRP0s8FRR9WpABURTiwQIhcrFVsykXUNzA/EvN80e9AgrWkf8XUM95YMYRJ+UYWXeFzjlW+o6Zk24jygbh3XLWjFWi3viT/+tBBCOvFK6E0=
go:
- 1.7
- master
before_script:
- go get github.com/Masterminds/glide
- go get -v -t github.com/markbates/pop/soda
- make deps
- soda create -e "test"
- soda migrate -e "test"
script:
- make test
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t $IMAGE:$COMMIT .
- docker tag $IMAGE:$COMMIT $IMAGE:latest
- docker tag $IMAGE:$COMMIT $IMAGE:travis-$TRAVIS_BUILD_NUMBER
- docker push $IMAGE
addons:
  code_climate:
    repo_token: 0c617dde8a5dc2e6870351abc96c4a689f147d0482bb795fe9e5c1e402c45a73
