language: go

services:
  - postgresql
go:
  - 1.7
  - master

before_script:
  - go get -v -t github.com/markbates/pop/soda
  - soda create -e "test"
  - soda migrate -e "test"

script:
  - go test -v -race ./...

addons:
  code_climate:
    repo_token: 0c617dde8a5dc2e6870351abc96c4a689f147d0482bb795fe9e5c1e402c45a73
