language: go

services:
  - postgresql

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.7
  - master

install:
  - go get github.com/Masterminds/glide
  - go get -v -t github.com/markbates/pop/soda 
  - make deps

before_script:
  - soda create -e "test"
  - soda migrate -e "test"

script:
  - make test

addons:
  code_climate:
    repo_token: 0c617dde8a5dc2e6870351abc96c4a689f147d0482bb795fe9e5c1e402c45a73
