language: go

services:
  - postgresql
go:
  - 1.7
  - master

before_script:
  - curl https://glide.sh/get | sh && glide install
  - soda create -e "test"
  - soda migrate -e "test"

script:
  - make test

addons:
  code_climate:
    repo_token: 0c617dde8a5dc2e6870351abc96c4a689f147d0482bb795fe9e5c1e402c45a73
