development:
  dialect: postgres
  database: gophercon_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: gcon_test
  user: postgres
  password: postgres
  host: 127.0.0.1

production:
  dialect: postgres
  database: gophercon_production
  user: gophercon
  password: {{ env "POSTGRES_PASSWORD" }}
  host: 127.0.0.1
  pool: 25
