development:
  dialect: postgres
  database: postgres
  user: postgres
  password: postgres
  host: db
  pool: 5

test:
  dialect: postgres
  database: gcon_test
  user: postgres
  password: postgres
  host: 127.0.0.1

production:
  dialect: postgres
  database: postgres
  user: postgres
  password: {{ env "POSTGRES_PASSWORD" }}
  host: gcon-sql
  pool: 25
