apiVersion: v1
kind: Service
metadata:
  name: gcon-sql
  labels:
    app: gcon
    tier: db
spec:
  ports:
  - port: 5432
    targetPort: sql
  selector:
    app: gcon
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
  labels:
    app: gcon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcon-sql
  labels:
    app: gcon
    tier: db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gcon
        tier: db
    spec:
      containers:
      - image: postgres:9.5
        name: postgres 
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: password
        ports:
        - containerPort: 5432
          name: sql
        volumeMounts:
        - name: pg-persistent-storage
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: pg-persistent-storage
        persistentVolumeClaim:
          claimName: pg-pv-claim
