apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gconweb
  labels:
    app: gconweb
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gconweb
    spec:
      containers:
        - image: bketelsen/gcon:2
          name: gconweb
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-pass
                key: password
          ports:
            - containerPort: 3000
              name: web
